### ISSUE TITLE
circular reference?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [davestewart/axios-actions#11]
It seems we have a circular reference here:

https://github.com/davestewart/axios-actions/blob/1dac8fe40687b6392add3ceb33d79dda72d193af/src/classes/ApiCore.ts#L1

https://github.com/davestewart/axios-actions/blob/1dac8fe40687b6392add3ceb33d79dda72d193af/src/classes/services/Http.ts#L2

**Comment by davestewart** [comment]
Yes. Looks like I rushed this one!

On it now...

**Comment by CharlesOkwuagwu** [comment]
how does 92cf8c6 fix this?

You still have the reference to ApiCore.ts from Http.ts
