### ISSUE TITLE
How do you send body data with post requests using ApiGroup?

### ISSUE THREAD

**Issue by nimabrownlee** [davestewart/axios-actions#16]
How do you do it? I dont find any examples in the docs. 

```
  const actions = {
    search: 'courses',
    update: 'POST products/widgets/:id',
    delete: 'DELETE products/widgets/:id',
  };
```

And the code below just replaces **id**.

 ` widgets.use('update', 1)`

But how can I send body data?

**Comment by davestewart** [comment]
Did you create a Group?

```js
export const widgets = new ApiGroup(axios, {
    search: 'courses',
    update: 'POST products/widgets/:id',
    delete: 'DELETE products/widgets/:id',
})

widgets.update({ id: 1, foo: 1 })
```

There's another ticket here, is that related?

- https://github.com/davestewart/axios-actions/issues/13

**Comment by nimabrownlee** [comment]
@davestewart 

Yes I am creating a group. 

`widgets.update({ id: 1, foo: 1 })`

But this code just replaces foo and id like this:

`products/widgets/:id/item/:foo`

becomes

`products/widgets/1/item/1`

but I am trying to send data. How do I do that? I dont think that the tickets are related.

**Comment by davestewart** [comment]
If you can update that last comment with full code so I can see what's happening, that would be helpful.

The URL will consume any placeholders, but the data should be sent in the POST body.

It's been a while since I looked at the code, so I might need to confirm if the full object is sent (I think it is) or the consumed fields are removed.

**Comment by nimabrownlee** [comment]
I am literally not doing anything beside following the example code in the docs for ApiGroup. That's why I am asking for help. You're completely right that the data should be sent through the POST body. But how do you do it? Do you have any examples I could look at?
Thanks.

**Comment by davestewart** [comment]
Oh, so this is a question not a bug?

Any data you pass will be sent through the post body.

Did you check the network panel?

From the demo:

![image](https://user-images.githubusercontent.com/132681/65064995-7a70e500-d979-11e9-8cd4-14801ec01d7e.png)

https://axios-actions.netlify.com/#/api/group

**Comment by davestewart** [comment]
Also:

- docs: https://github.com/davestewart/axios-actions/tree/master/docs
- ApiGroup docs: https://github.com/davestewart/axios-actions/blob/master/docs/classes/ApiGroup.md

**Comment by nimabrownlee** [comment]
@davestewart 

Yes this is a question. The example code is in vue so I dont really understand it. Could you please post some examples in vanilla js? Its a really simple question. How do I send data with post requests? If I had a login route, how would I send the email & password?
And I've looked at the docs several times and I dont find any examples. If you find any, then please post them here.

**Comment by davestewart** [comment]
> And I've looked at the docs several times and I dont find any examples.

This is the docs index page; every page has multiple examples, all in vanilla JS:

![image](https://user-images.githubusercontent.com/132681/65142922-a89f0500-da0b-11e9-9ffa-769f170de166.png)

If you can't find or understand the examples, then that's not something I can help you with.

If you had a login route, you'd probably just send the username and password with a normal API call; AxiosActions is designed for sets of actions that you don't want to repeat in multiple places.

A login will only be in one place.

**Comment by nimabrownlee** [comment]
@davestewart 

Arent you one of the contributors? How can you not help me?

```
const widgets = new ApiGroup(axios, {
    login: 'api/login'
})
```

`widgets.call(login).then()`

The code above exec the login action and gets the response. Now where in this code can I send the login info? I dont know why you keep referring to the docs because they dont have any examples...

**Comment by davestewart** [comment]
> How can you not help me?

I already did:

- https://github.com/davestewart/axios-actions/issues/16#issuecomment-532021820

> I dont know why you keep referring to the docs because they dont have any examples

Every page has multiple usage examples:

- https://github.com/davestewart/axios-actions/blob/master/docs/classes/ApiGroup.md#usage

There is also a working demo for every class...

- https://axios-actions.netlify.com/#/api/group

...each of which links to the related:

- example file
- source code
- docs for that class
