### ISSUE TITLE
How do we specify additional headers in ApiGroup

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [davestewart/axios-actions#4]
Say we need a POST action for file upload, typically we would need to specify headers for example, with just axios i can do:

`Api().post('upload/', formData, {headers: {'content-type': 'multipart/form-data'}})`

How may we set specific headers on an item in ApiGroup?

```
export const widgets = new ApiGroup(axios, {
  view: 'api/products/widgets?category=:category',
  load: 'api/products/widgets/:id',
  upload: 'POST api/upload/:context' // need to add headers specific to just this function
})
```

**Comment by davestewart** [comment]
Hey Charles, 

Currently no way to do this, but it seems like a great feature request!

I'll take a look.

**Comment by davestewart** [comment]
@CharlesOkwuagwu - sorry, I dropped the ball on this one!

Let me look at this, this week :)

**Comment by davestewart** [comment]
OK, so this is done in the [headers](/davestewart/axios-actions/tree/feature/headers) branch.

I have to update the readme, which I'll do today, then I'll release as v3.0.0

**Comment by davestewart** [comment]
@CharlesOkwuagwu 

Fixed in 2d8625bfabe392aaab7b936c1229fa9110b6ddb8

Documentation here:

- https://github.com/davestewart/axios-actions/blob/master/docs/config.md

**Comment by robjbrain** [comment]
Hi @davestewart does this work with ApiEndpoint? I can't seem to get it to (I have updated the latest branch to be sure).

I have one that looks like this:

```
export const submissionsApi = new ApiEndpoint(axios, {
    index: 'GET /api/submissions',
    //store: 'POST /api/submissions',
    store: {url: '/api/submissions', method: 'post', headers: {'content-type': 'multipart/form-data'}}
})
```

And for some reason:
`store: 'POST /api/submissions'` works perfectly as does `store: {url: '/api/submissions', method: 'post'` but when using `multipart/form-data` no data is sent at all.

Of course i'm attempting to send a file here, but even totally removing the file and just having two simple text and number inputs the data doesn't get sent.

```
submissionsApi
    .store({
        description: 'this is test',
        group_id: 123,
    })
```

The only difference I can see when inspecting the requests is this:

`Content-Type: multipart/form-data` vs `Content-Type: application/json;charset=UTF-8`

Obviously that's the change I made.

So it seems like the json object doesn't get sent when you change the content-type. 

Is there a way around this? I presume it's something obvious but I can't figure it out. I've found various references to using the `FormData` class when looking online for solutions (https://stackoverflow.com/questions/49478991/post-file-along-with-form-data-vue-axios).

But sending a FormData object doesn't make any difference:

e.g:

```
let formData = new FormData()
//formData.append('file', file)//Javascript File Object
formData.append('description', 'this is text')
formData.append('group_id', 1234)

submissionsApi.store(formData)
```

Again no data is sent, even though I wasn't attempting to send a file, just a string and a number.

**Comment by davestewart** [comment]
Hey @robjbrain - sorry to leave this for a few days - finding it really tricky to balance work and OS at the moment. I need to put some effort into a few projects over the next few days, so let me take a look.

One thing that would be useful to me - can you make a new ticket with this request? That way if something needs to be fixed, I can reference the issue more easily.

Thanks!
